#!/bin/sh

#. /lib/live/config.sh

## live-config(7) - System Configuration Components
## Copyright (C) 2016-2020 The Debian Live team
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


#set -e

LIVE_CONFIG_CMDLINE=$(cat /proc/cmdline)

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.hotspot=*|hotspot=*)
				LIVE_HOTSPOT="${_PARAMETER#*hotspot=}"
				;;
		esac
	done
}

Init ()
{
	# Checking if a locale package is installed
	if ! pkg_is_installed "locales" && \
	   ! pkg_is_installed "locales-all"
	then
		exit 0
	fi
	# Checking if the locale has already been configured
	if component_was_executed "locales"
	then
		exit 0
	fi

	echo -n " locales"
}

Config ()
{

if test -n "$LIVE_HOTSPOT"; then

     cat <<EOF > /etc/systemd/system/make-accesspoint.service
[Unit]
Description=Setup Hotspot
After=network.target

[Service]
Type=oneshot
ExecStart=/etc/ltsp/make-hotspot $LIVE_HOTSPOT
#RemainAfterExit=true
#ExecStop=/opt/foo/teardown-foo.sh
#StandardOutput=journal

[Install]
WantedBy=multi-user.target
EOF

     /usr/bin/systemctl enable make-accesspoint.service
fi

}

Cmdline
#Init
Config
